### ISSUE TITLE
Work with system python?

### ISSUE THREAD

**Issue by tmalsburg** [bnicenboim/pangoling#3]
```
Processing using causal model 'gpt2'...
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.
```

Is there a way to make this work with an existing Python install?

Thanks for sharing this package!

**Comment by tmalsburg** [comment]
To answer my own question: It was as easy as installing Python packages `transformers` and `PyTorch` using: 

``` sh
pip install transformers
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
```

Second line is for the CPU (i.e. non-CUDA) version of PyTorch.

**Comment by bnicenboim** [comment]
oh, and did it work now?
(Not finding the right python is a reticulate issue. I know that Rstudio lets you define where python is in its options, and it can also be set manually with one of these system option but I don't remember how)

**Comment by tmalsburg** [comment]
It does work as expected.  Just confirmed it.  Produces the same log probs as in your example.  This is on Ubuntu 22.04.

**Comment by tmalsburg** [comment]
Perhaps add this info to README for other users.

**Comment by bnicenboim** [comment]
not sure what really happened, it did find your python but not the packages then? Because you get the same error when reticulate cannot find your python.

**Comment by tmalsburg** [comment]
> it did find your python but not the packages then?

I guess that must have been the case.  Only thing I did was to install the two packages and then it worked.
